language: generic 

# super level permissions req in order to build
sudo: required
# tell travis we need a copy of docker running
services:
    - docker
# Build our image using Dockerfile.dev
before_install:
    - docker build -t alanhood77/docker-react -f Dockerfile.dev .
# Tell Travis how to run our test suite
script:
    - docker run -e CI=true alanhood77/docker-react npm run test
# Tell Travis how to deploy our code to AWS