language: generic 

# super level permissions req in order to build
sudo: required
# tell travis we need a copy of docker running
services:
    - docker
# Build our image using Dockerfile.dev
before_install:
    - docker build -t alanhood77/docker-react -f Dockerfile.dev .
# Tell Travis how to run our test suite
script:
    - docker run -e CI=true alanhood77/docker-react npm run test
# Tell Travis how to deploy our code to AWS
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-project"
    env: "DockerReactProject-env"
    bucket_name: "elasticbeanstalk-us-east-2-320300331640"
    bucket_path: "docker-react-project"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY